Urban Data Science & Smart Cities <br>
URSP688Y Spring 2026<br>
Instructor: Chester Harvey <br>
Urban Studies & Planning <br>
National Center for Smart Growth <br>
University of Maryland

# Demo 5 - Accessing and Wrangling Data from the Web

- Loading Data from the Web with APIs
- Storing Code in Modules

## APIs (Application Programming Interfaces)

APIs are an interface for accessing information. At the most general level, nearly all programs that can be accessed with code have an API.

Python functions, for example, are programs with APIs. You access them by calling the function name and defining arguments.

In practice, when people talk about getting data from APIs they are usually talking about web APIs
- These are usually designed with a software architecture called [REST](https://en.wikipedia.org/wiki/REST).
- Using a REST API involves making a request to a URL and receiving a response.
- Often, that response is in a format called [JSON](https://en.wikipedia.org/wiki/JSON), which is structured like nested dictionaries and lists.

Today, we're going to practice retrieving data about cities from web APIs, then wrangling the data they return into a tabular format we can analyze.

Making a request to an API is just another way to get data, similar to downloading it from an open data portal. Why would you bother querying an API instead of just downloading a table?
- APIs allow programmatic access to data that can be easily scaled, replicated, and documented
- APIs can allow customization of which data you are accessing
- JSON allows for much more complex data structures than downloadable tables
- APIs can be an easy way to access real-time data
- Can we think of other reasons?

### Capital Bikeshare Data — Free, simple, real-time

Some APIs with data about cities are free and simple. The Capital Bikeshare (CABI) system, for example, has an API that reports on the status of bikes in its system in real-time. It's available free as part of CABI's operating agreement with the City of Washington, D.C.

The District Department of Transportation (DDOT) lists APIs for all of the micromobility systems operating in the city on [this webpage](https://ddot.dc.gov/page/dockless-api).

Let's request some data from the CABI systems and see what it looks like.

- What could we do with these data?
- What are its limitations?

You may need to install PyYAML, a package for working with YAML-formatted files

`pip install PyYAML`

In [1]:
# Import package dependencies
import pandas as pd
import requests # for making RESTful API requests
import json # for converting strings in JSON format to python dictionaries and lists
import yaml # for converting yaml-structured text into python dictionaries and lists
import os # for basic operating system functions, like compiling paths

In [2]:
# Making a "GET" request
response = requests.get('https://gbfs.lyft.com/gbfs/1.1/dca-cabi/en/free_bike_status.json')

# Get JSON content
data = response.json()

In [3]:
# Preview the data
data

{'data': {'bikes': [{'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.898367167,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '450-3538',
    'bike_id': '1347d091476ed6e388578d2b355236fb',
    'lon': -77.043296456},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.887048244,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '813-9735',
    'bike_id': 'f1ccc4293f38cd39f5d45b2c5538a5ba',
    'lon': -77.0137012},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.894212723,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '430-1461',
    'bike_id': 'c069b6741a412b328cb93338e453b974',
    'lon': -77.094623208},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.908170104,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '689-6666',
    'bike_id': 'd3f6a36482773b85ab5e4556fcd96d23',
    'lon': -77.035774469},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.99846983,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '531-7110',
    'bike_id': '5e12f3fa2875be6ad69077c5c5977311',
    'lon': -77.040771961},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.908878565,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '339-0820',
    'bike_id': 'd72f54d25435b2ff226daeb1d30520cf',
    'lon': -77.001096725},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.880540371,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '439-5356',
    'bike_id': '0768528d8da612cb1ecacc98940bba07',
    'lon': -77.025262594},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.845176458,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '784-7460',
    'bike_id': 'ea178216409fc84c9773b21fd5c9329f',
    'lon': -77.00797236},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.883964777,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '222-1844',
    'bike_id': '28f60ed1f30ce1f31a8b03699cd47c82',
    'lon': -77.100602031},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.942220449,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '492-9212',
    'bike_id': 'f834db78bd7218b3aee1e4dd33a1fc38',
    'lon': -77.001872659},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.807651162,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '543-0533',
    'bike_id': '921831af37d481443a6642b3a76347c6',
    'lon': -77.07893312},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.865575671,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '798-7084',
    'bike_id': '8928889ed63e0b60650042b9624586e9',
    'lon': -77.087473512},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.85569942,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '816-0046',
    'bike_id': 'da5d59c62fc3b3f5bb2d0724666845b0',
    'lon': -77.113196015},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.871827483,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '552-6470',
    'bike_id': '3e42b14781d1822f828f82e209b00d0b',
    'lon': -77.132653356},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.901970267,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '624-6045',
    'bike_id': 'b7e5f83cc0f428ef06883a85489ed3d4',
    'lon': -77.038488507},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.852710724,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '469-8627',
    'bike_id': 'e927376b9306ebe9c990b0bdeed3830b',
    'lon': -77.053614855},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.886150002,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '441-6475',
    'bike_id': 'e16911c7265293ea9bfce72de1aa5751',
    'lon': -77.165204287},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.883796692,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '801-2163',
    'bike_id': '1a8e8f6fa41767daf1f86fe5729e9d10',
    'lon': -77.10018599},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.907897592,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '570-0356',
    'bike_id': 'd40ad3f1cac09314a50e73b42fc8fc5f',
    'lon': -77.071662903},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.940657496,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '471-3434',
    'bike_id': '7ac51cc89803204aa5558386518f20c2',
    'lon': -77.004225254},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.901322484,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '279-0210',
    'bike_id': '476eee6c67f74a175e82b315d6b99c09',
    'lon': -77.043501735},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.905347466,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '475-5344',
    'bike_id': 'edb60bffb44753e090cdbde43bcdc158',
    'lon': -77.030595779},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.923990965,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '611-4789',
    'bike_id': 'b300d475dc2acfbd880b5611b8c684d0',
    'lon': -77.040863276},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.870517969,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '892-1934',
    'bike_id': 'b58e729c513bc6e3e1bbd3cf273bde41',
    'lon': -77.009431243},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.896592379,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '682-7646',
    'bike_id': '5a5a1ab7069010b4a411c1ba991337e4',
    'lon': -77.096231818},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.9094491,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '471-0786',
    'bike_id': '3db698be1f72934a09590c20b406d4f5',
    'lon': -77.054798484},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.923393488,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '309-6260',
    'bike_id': 'c985c10d3fad9881086ba2d7f609c2f2',
    'lon': -76.972284794},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.896586299,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '459-9544',
    'bike_id': 'd825d0859d9e49007f89019353700af2',
    'lon': -77.039817929},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.936098933,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '379-0664',
    'bike_id': 'baf4179b36beddd827d2d8b7eca438bf',
    'lon': -76.973202109},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.899010897,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '342-5162',
    'bike_id': '8060a0ce12047cd633978a6c29ec204d',
    'lon': -77.033413529},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.870634317,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '226-9819',
    'bike_id': 'd6dcb51714122c805f3d683319ceb055',
    'lon': -77.150902033},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.895717978,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '581-5022',
    'bike_id': '843d86ae8d83f8d0a0c27893822837f5',
    'lon': -77.029772162},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.900976299999996,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '805-0031',
    'bike_id': '78e9cb41ce48a868d9efe3f3ba697106',
    'lon': -77.028005838},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.884790659,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '417-7051',
    'bike_id': 'd9a871ac547a400481b86f43a8987bf2',
    'lon': -77.005928874},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.896083236,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '594-5514',
    'bike_id': 'ee2efd06ee630b2c4eb1fadf2a84e5a2',
    'lon': -77.049583912},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.835095048,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '265-5892',
    'bike_id': '26d63ac51666410527603b970f662fe1',
    'lon': -77.114087105},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.84845531,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '714-6566',
    'bike_id': '51bb18e6bd8e8e83c32732e2596cbb42',
    'lon': -77.272890449},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.879799843,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '564-9397',
    'bike_id': '0bcbf09aa1a75a46bd9f6839f2a24063',
    'lon': -77.037705898},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.906309843,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '546-3518',
    'bike_id': 'd32f8b6150b1c9821d8c40c47104da9a',
    'lon': -77.009884119},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.905709386,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '369-0690',
    'bike_id': 'd1f5e1d944a58b40b8fc8388948d6469',
    'lon': -77.043557048},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.934238315,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '584-6696',
    'bike_id': '8e9f294c7c529f0d83d6c10ccdc391e6',
    'lon': -76.994590998},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.902969837,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '793-4151',
    'bike_id': '116b4ab40ea3e262ce984e2cb6297909',
    'lon': -77.060010314},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.894105434,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '457-5494',
    'bike_id': 'f0f45f9b3f55ef312e69602ef266b0c2',
    'lon': -77.162148595},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.834972143,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '487-0069',
    'bike_id': 'eceadd623461909d2a8b075ca52695d3',
    'lon': -77.064423561},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.87046957,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '563-4365',
    'bike_id': 'ca33b0156a1efbf11971cecac63f68d6',
    'lon': -77.009451032},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.953251719,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '525-5138',
    'bike_id': 'cc5bbf25ab4c0d3a9ccf5109dcfd1740',
    'lon': -77.085065842},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.898177266,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '454-8459',
    'bike_id': '33cedb66d51d62486ac672b8cf73389c',
    'lon': -77.032292604},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.909491658,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '703-9951',
    'bike_id': '92d361ff7b6d0bb664ee4ea7c5539df6',
    'lon': -76.988697529},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.961666346,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '798-1368',
    'bike_id': '3593dda297acb0811e8cc4d871e2ffdb',
    'lon': -77.086032748},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.901682973,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '590-6904',
    'bike_id': 'bcdd7b4202121e9007afc7bd7c0efcf5',
    'lon': -77.044996381},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.904787898,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '281-5140',
    'bike_id': 'd798a17dc31713c69bf51db11ea403e2',
    'lon': -77.043611526},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.908794403,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '851-1438',
    'bike_id': '99ff3c99770cb412efd1e3abb9152003',
    'lon': -77.148465872},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.881638408,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '608-3927',
    'bike_id': 'c8fbb421507a07e480e0f5b2af7fdbb0',
    'lon': -77.027661085},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.898961306,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
     'ios': 'https://dc.lft.to/lastmile_qr_scan'},
    'name': '660-2148',
    'bike_id': 'b885e493ef2b5e62f053305bdee55ed9',
    'lon': -77.033280611},
   {'is_disabled': 0,
    'type': 'electric_bike',
    'lat': 38.898456573,
    'is_reserved': 0,
    'fusion_lat': 0.0,
    'fusion_lon': 0.0,
    'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',

In [4]:
# Inspect the keys
data.keys()

dict_keys(['data', 'last_updated', 'ttl', 'version'])

In [6]:
data["last_updated"]

1774546105

In [12]:
data['data']['bikes'][:1]

[{'is_disabled': 0,
  'type': 'electric_bike',
  'lat': 38.898367167,
  'is_reserved': 0,
  'fusion_lat': 0.0,
  'fusion_lon': 0.0,
  'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
   'ios': 'https://dc.lft.to/lastmile_qr_scan'},
  'name': '450-3538',
  'bike_id': '1347d091476ed6e388578d2b355236fb',
  'lon': -77.043296456}]

In [10]:
electric = 0
for bike in data["data"]["bikes"]:
    if bike["type"] == "electric_bike":
        electric += 1
#data["data"]["bikes"][0]

In [16]:
data['data']['bikes'][1]

{'is_disabled': 0,
 'type': 'electric_bike',
 'lat': 38.887048244,
 'is_reserved': 0,
 'fusion_lat': 0.0,
 'fusion_lon': 0.0,
 'rental_uris': {'android': 'https://dc.lft.to/lastmile_qr_scan',
  'ios': 'https://dc.lft.to/lastmile_qr_scan'},
 'name': '813-9735',
 'bike_id': 'f1ccc4293f38cd39f5d45b2c5538a5ba',
 'lon': -77.0137012}

In [13]:
# Make a dataframe out of data for available bikes
df = pd.DataFrame(data['data']['bikes'])

df.head()

,is_disabled,type,lat,is_reserved,fusion_lat,fusion_lon,rental_uris,name,bike_id,lon
0,0,electric_bike,38.898367,0,0.0,0.0,{'android': 'https://dc.lft.to/lastmile_qr_sca...,450-3538,1347d091476ed6e388578d2b355236fb,-77.043296
1,0,electric_bike,38.887048,0,0.0,0.0,{'android': 'https://dc.lft.to/lastmile_qr_sca...,813-9735,f1ccc4293f38cd39f5d45b2c5538a5ba,-77.013701
2,0,electric_bike,38.894213,0,0.0,0.0,{'android': 'https://dc.lft.to/lastmile_qr_sca...,430-1461,c069b6741a412b328cb93338e453b974,-77.094623
3,0,electric_bike,38.908170,0,0.0,0.0,{'android': 'https://dc.lft.to/lastmile_qr_sca...,689-6666,d3f6a36482773b85ab5e4556fcd96d23,-77.035774
4,0,electric_bike,38.998470,0,0.0,0.0,{'android': 'https://dc.lft.to/lastmile_qr_sca...,531-7110,5e12f3fa2875be6ad69077c5c5977311,-77.040772

In [14]:
df["type"].value_counts()

type
electric_bike    887
Name: count, dtype: int64

In [17]:
# Save the json data for later

def save_json(data, file_name, timestamp=False):
    """Save data as json file
    data: json-compatable data structure (nested dicts and lists)
    file_name: string for file name; DO NOT include file extension (e.g., ".json")
    """
    if timestamp:
        file_name = f'{file_name}_{timestamp}.json'
    else:
        file_name = f'{file_name}.json'
    with open(file_name, 'w') as f:
        json.dump(data, f, indent=4)

save_json(data, 'cabi_data')

In [ ]:
# Make an automated workflow to retrieve data and save it, all at once

def get_and_save_cabi_data():
    """Get current data from the CABI API and save as a timestamped JSON
    """
    # Making a "GET" request
    response = requests.get('https://gbfs.lyft.com/gbfs/1.1/dca-cabi/en/free_bike_status.json')
    # Get JSON content
    data = response.json()
    # Get timestamp from data
    timestamp = data['last_updated']
    # Save to file
    save_json(data, 'cabi_data', timestamp)

In [ ]:
# Run the automated workflow
# Could we do this on a schedule to collect "snapshots" of the state of the CABI system?
get_and_save_cabi_data()

### Rentcast — Paid, more complex, updated less frequently

Free APIs like for CABI are becoming less common. (Does this sound familiar in light of today's reading about smart cities as emerging markets?) Many other APIs require that you pay for data, either through a subscription or for request you make. Some have free tiers, but they're usually quite limited.

Several years ago, Zillow provided data about real estate markets through a free API available to the public. You now have to go through a complicated application process to get access to their API, and your use case needs to be aligned with their business model.

An alternative source of real estate data is a company called [Rentcast](https://www.rentcast.io/). They allow anyone to set up an account and purchase data through an API, and it [gets expensive fast](https://www.rentcast.io/api#api-pricing). You get 50 requests free for "development," but after that you pay \\$0.20 per request or \\$74 per month for a subscription to make up to 1,000 requests.

They keep track of who is making requests with an 'API key', which is a long string of characters you include in your request as a 'header'. Because API keys are attached to billing information (i.e., your credit card), they're very sensitive. You ***NEVER*** want to commit your API key to GitHub or share it anywhere else publicly.

It's best practice to store your API key in a separate file—I like to use a format called YAML—that you prevent from being committed by adding it to your respository's `.gitignore` file. This is a list of files that you explicitly tell git not to keep track of.

When you want to use your API key, you load the configs into memory in the Python kernel you're currently working in. When you close or restart the kernel, the computer forgets it.

In [21]:
# Load personal data from a configs file (API key, local data path)
with open('configs.yaml', 'r') as file:
    CONFIGS = yaml.safe_load(file)

FileNotFoundError: [Errno 2] No such file or directory: 'configs.yaml'

In [19]:
# Load eviction data we used last week
df = pd.read_csv('District_Court_of_Maryland_Eviction_Case_Data_MG_PG.csv')

In [20]:
# Preview columns
df.head(1)

,Unnamed: 0,Event Date,Event Type,Event Comment,County,Location,Tenant City,Tenant State,Tenant ZIP Code,Case Type,Case Number,Evicted Date,Event Year,Eviction Year
0,535,01/03/2023,Warrant of Restitution - Return of Service - E...,NaN,Montgomery,Rockville,Silver Spring,MD,20910.0,Failure to Pay Rent,D-061-LT-22-004107,12/08/2022,2023,2022.0

In [ ]:
# def construct_rentcast_json_filename(zipcode):
#     return f'rentcast_{zipcode}.json'

# def get_rentcast_data_for_zipcode(zipcode):
#     # Make GET request to rentcast API
#     url = f'https://api.rentcast.io/v1/markets?zipCode={zipcode}&dataType=All&historyRange=6'
#     headers = {
#         'X-Api-Key': CONFIGS['rentcast_api_key'],
#         'Accept': 'application/json', 
#     }
#     response = requests.get(url, headers=headers)
#     data = response.json()
#     # Save to json
#     file_path = construct_rentcast_json_filename(zipcode)
#     with open(file_path, 'w') as file:
#         json.dump(data, file, indent=4)

# # Get rentcast market data for the 5 zipcodes most represented in the eviction case data
# zipcodes = df['Tenant ZIP Code'].value_counts().head(1).index.astype('Int64')

# for zipcode in zipcodes:
#     get_rentcast_data_for_zipcode(zipcode)

NameError: name 'CONFIGS' is not defined

In [ ]:
# Preview the data
filename = construct_rentcast_json_filename(zipcode)
with open(filename, 'r') as file_object:
    data_dict = json.load(file_object)

data.keys()

In [ ]:
data['saleData'].keys()

In [ ]:
data['saleData']['dataByPropertyType'][0]

## Storing Code in Modules

When writing more complicated code, it can be really helpful to store it in separate files so it doesn't clutter up your notebook. This also makes it easier to use in multiple places. For example, multiple notebooks could access utility functions store in a single custom module.

Can you store functions used to query the APIs above in a separate module, then load and run them in this notebook?

In [23]:
import demo08

In [24]:
dir(demo08)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__']